-- Q1 Traditional JOIN
SELECT b.TITLE, b.CATEGORY, p.NAME AS "PUBLISHER NAME"
FROM BOOKS b, PUBLISHER p
WHERE b.PUBID = p.PUBID 
AND b.CATEGORY LIKE 'FAMILY LIFE';

-- Q1 JOIN ON
SELECT b.TITLE, b.CATEGORY, p.NAME AS "PUBLISHER NAME"
FROM BOOKS b JOIN PUBLISHER p
ON b.PUBID = p.PUBID
WHERE b.CATEGORY LIKE 'FAMILY LIFE';

-- Q2 TRADITIONAL JOIN
SELECT c.LASTNAME||', '||c.FIRSTNAME AS "NAME", o.ORDER#
FROM CUSTOMERS c, ORDERS o
WHERE c.CUSTOMER# = o.CUSTOMER#
AND c.FIRSTNAME LIKE 'JASMINE'
AND c.LASTNAME LIKE 'LEE';

-- Q2 JOIN ON
SELECT c.LASTNAME||', '||c.FIRSTNAME AS "NAME", o.ORDER#
FROM CUSTOMERS c JOIN ORDERS o
ON c.CUSTOMER# = o.CUSTOMER#
WHERE c.FIRSTNAME LIKE 'JASMINE'
AND c.LASTNAME LIKE 'LEE';

-- Q3 TRADITIONAL JOIN
SELECT a.LNAME||', '||a.FNAME AS "AUTHOR NAME", b.TITLE, b.CATEGORY
FROM BOOKS b, BOOKAUTHOR ba, AUTHOR a
WHERE b.ISBN = ba.ISBN
AND ba.AUTHORID = a.AUTHORID
AND b.CATEGORY LIKE 'BUSINESS';

-- Q3 JOIN ON
SELECT a.LNAME||', '||a.FNAME AS "AUTHOR NAME", b.TITLE, b.CATEGORY
FROM BOOKS b JOIN BOOKAUTHOR ba
ON b.ISBN = ba.ISBN JOIN AUTHOR a
ON ba.AUTHORID = a.AUTHORID
WHERE b.CATEGORY LIKE 'BUSINESS';

-- Q4 TRADITIONAL JOIN
SELECT a.LNAME||', '||a.FNAME AS "AUTHOR NAME", b.TITLE, b.COST
FROM BOOKS b, BOOKAUTHOR ba, AUTHOR a
WHERE b.ISBN = ba.ISBN
AND ba.AUTHORID = a.AUTHORID
AND b.COST > 40;

-- Q4 JOIN ON
SELECT a.LNAME||', '||a.FNAME AS "AUTHOR NAME", b.TITLE, b.COST
FROM BOOKS b JOIN BOOKAUTHOR ba
ON b.ISBN = ba.ISBN JOIN AUTHOR a
ON ba.AUTHORID = a.AUTHORID
WHERE b.COST > 40;
